# Generated by Django 2.2.12 on 2020-06-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date', 'title'], 'verbose_name': 'Publicación'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Etiqueta'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Borrador'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima modificación'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
