# Generated by Django 2.2.12 on 2020-06-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200602_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date', 'title'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
    ]
