# Generated by Django 2.2.12 on 2020-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200603_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
