# Generated by Django 2.2.12 on 2020-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='uploads/% Y/% m/% d/', verbose_name='Imagen'),
        ),
    ]
