# Generated by Django 2.2.12 on 2020-06-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200603_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='uploads',
        ),
    ]
