# Generated by Django 2.2.12 on 2020-06-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200603_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='externalURL',
            field=models.URLField(blank=True),
        ),
    ]
