# Generated by Django 2.2.12 on 2020-06-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_externalurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='externalURL',
        ),
    ]
