# Generated by Django 2.2.12 on 2020-06-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_externalurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uploads',
            new_name='image',
        ),
    ]
